org.gradle.jvmargs = -Xmx4096M
org.gradle.parallel = true

test.recipe_viewer = emi

mod.name = Condiments
mod.id = condiments
mod.version = 1.4.8
mod.authors = chililisoup
mod.license = MIT
mod.description = A variety of Vanilla+ features to add some extra flavor to your modded Minecraft game!
mod.homepage = https://modrinth.com/mod/condiments
mod.sources = https://github.com/chililisoup/Condiments
mod.issues = https://github.com/chililisoup/Condiments/issues
mod.group = dev.chililisoup

deps.fabric_loader = 0.18.4